version: '3.9'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  api:
    build:
      context: ../
      dockerfile: infra/docker/api.Dockerfile
    depends_on:
      - db
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
    ports:
      - "8080:8080"
  web:
    build:
      context: ../
      dockerfile: infra/docker/web.Dockerfile
    depends_on:
      - api
    ports:
      - "3000:3000"
volumes:
  pgdata:
