version: '3.9'

services:
  db:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: todo
      POSTGRES_USER: todo
      POSTGRES_PASSWORD: todo
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  api:
    build:
      context: ../api
      dockerfile: Dockerfile
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/todo
      SPRING_DATASOURCE_USERNAME: todo
      SPRING_DATASOURCE_PASSWORD: todo
      SPRING_PROFILES_ACTIVE: docker
    ports:
      - '8080:8080'
  web:
    build:
      context: ../web
      dockerfile: Dockerfile
    depends_on:
      - api
    environment:
      NEXT_PUBLIC_API_BASE_URL: http://localhost:8080/api
    ports:
      - '3000:3000'
volumes:
  postgres_data:
