spring:
  application:
    name: todo-api
  datasource:
    url: jdbc:postgresql://localhost:5432/todo
    username: todo
    password: todo
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  flyway:
    enabled: true
    locations: classpath:db/migration

logging:
  level:
    root: INFO

server:
  port: 8080
